### ISSUE TITLE
spaces around = in function keyword arguments.

### ISSUE THREAD

**Issue by atbug** [julia-vscode/DocumentFormat.jl#88] opened 2020-03-26 19:13 UTC
It seems no matter how I tune
```json
{
    "julia.format.ops": false,
    "julia.format.kw": false
}
```

The function
```julia
function foo(x; y::Int64=1)
    xx = x * 1
    yy = y + 1
    return xx + yy
end
```
will be formatted to 
```julia
function foo(x; y::Int64 = 1)
    xx = x * 1
    yy = y + 1
    return xx + yy
end
```
which is not the expected behavior.

julia version: official 1.4.0 windows binary
vscode-plugin version: 0.15.18

**Comment by davidanthoff** [comment] 2020-03-27 20:10
I've moved the issue to this repo here, where the implementation lives.

**Comment by ZacLN** [comment] 2020-05-29 14:14
https://github.com/julia-vscode/LanguageServer.jl/pull/717

**Comment by atbug** [comment] 2020-06-09 16:34
I can still reproduce with both `julia` and `julia-insider`. Is this issue resolved, or did I misunderstand?

```julia
function foo(x; y::Int64 = 1)
    xx = x * 1
    yy = y + 1
    return xx + yy
end
```
should be formatted to
```julia
function foo(x; y::Int64=1)
    xx = x * 1
    yy = y + 1
    return xx + yy
end
```
No?

**Comment by non-Jedi** [comment] 2020-06-09 16:48
Duplicate of #102. Closing this one since #102 has more discussion.

**Closed by non-Jedi** 2020-06-09 16:48 UTC
Labels: enhancement
